### ISSUE TITLE
Empty Module Name

### ISSUE THREAD

**Issue by HenrietteRoeger** [streamlio/heron-python-tutorial#2]
When I submit the topology, I get a "Empty Module Name" error.

_Topology Word_Count_Topology failed to be loaded from the given pex: Empty module name_

Where could that come from? do I need a __main__.py file?

Cheers Henriette

**Comment by aahmed-se** [comment]
What's the version of heron you are deploying against.

**Comment by HenrietteRoeger** [comment]
The version is quite new: 
0.16.3

(Great and very helpful tutorial though!! )

**Comment by aahmed-se** [comment]
Hi Henriette, I need to update the example and bring it up to a new version of heron which is 0.17.1 , it should work against 0.15.0 today as is. I will push the update to 0.17.1 over the weekend.

**Comment by HenrietteRoeger** [comment]
Thank you so much! Do you know what the problem is or could give me a hint so I could try it myself in my own project?

**Comment by aahmed-se** [comment]
the basic issue is that the current tutorial is targeting 0.15.0

https://github.com/streamlio/heron-python-tutorial/blob/master/3rdparty/python/requirements.txt

depending on the sever version that needs to be changed and the source code update for the new api changes.
